name: Deploy to Github pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  install-gha: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/setup-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

